language: rust

cache: 
  - cargo

before_script: 
  - set +e

script:
  - cargo build --all
  - cargo test --all

before_deploy:
  - cargo doc --all
  - echo '<meta http-equiv=refresh content=0;url=outdated_runner/index.html>' > target/doc/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: target/doc
  keep-history: true
  on:
    branch: master

before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never